name: Deploy Docusaurus to GitHub Pages

# this flow will be ran and applied when push code to github
on:
  push:
    branches:
      - master
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-acnptions#on

jobs:
  # decide jobs named build
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    steps:
      # fetch all of code from repository to build
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # install node js v24
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      # run 'npm ci' to install depedencies according to 'package-lock.json'
      - name: Install dependencies
        run: npm ci

      # build website
      - name: Build website
        run: npm run build

      # upload build/ folder in order to be gotten by job deploy 
      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    name: Deploy to GitHub Pages
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    # Memberikan izin khusus ke GitHub Actions supaya bisa mengunggah hasil ke GitHub Pages.
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # send build result to GitHub Pages using official action from GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
